# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: anj.digital
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.


  Next para lorem ipsum
baseurl: "" # the subpath of your site, e.g. /blog
# domain: joseryzmal.dev
# url: "https://anj.digital"
twitter_username: jekyllrb
github_username:  jekyll

profile_name: Angela
profile_title: Digital Product Designer
linkedin_url: https://www.linkedin.com/in/angelasalano/
external_url: https://anj.digital
behance_url: https://www.behance.net/AngelaSalano
about: >-
  It’s been my joy and passion creating scalable and easy-to-use digital products for users. I specialize in creating digital designs, responsive website interfaces, and UI screens for mobile apps.


  My journey has been from Graphic Design and Multimedia Digital to Digital Product Design. I am a multi-skilled professional with a love for Design Systems and defining Screen Flows.


  I am also knowledgeable at using different Content Management Systems having experience with Joomla, Drupal, Wordpress, and Magento.


  With exposure from different industries: Digital News, Telco/IT, E-commerce, and Marketing, I am able to quickly learn different processes. I am flexible, collaborative, and able to adapt with the ever-changing landscape of my chosen career.
skills:
  - title: UI/UX Design
    rating: 5/5
  - title: Wireframing
    rating: 5/5
  - title: Prototyping
    rating: 4/5
  - title: Design Systems
    rating: 5/5
  - title: Graphic Design
    rating: 5/5
  - title: Data Visualization
    rating: 5/5
  - title: Video Editing
    rating: 4/5
  - title: HTML + CSS
    rating: 3/5

education:
  - title: Design for the 21st Century
    details: >-
      Interaction Design Foundation (IxDF)

      Issued Mar 2022

      Credential ID 94627-2022-661627
  - title: Web Design for Usability
    details: >-
      Interaction Design Foundation (IxDF)

      Issued Mar 2021

      Credential ID 946272021508917
  - title: Foundation Certificate in User Experience
    details: >-
      BCS, The Chartered Institute for IT

      Issued Dec 2019

      Credential ID 00473208 / Candidate Number: SJ37964551
  - title: De La Salle-College of Saint Benilde
    details: AB Multimedia Arts, 2012

collections:
  work_experiences:
    sort_by: index

defaults:
  - scope:
      path: ""
    values:
      layout: default
      title: anj.digital

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - package.json
  - tailwind.config.js
  - yarn.lock
  - assets/css/tailwind.css

gtm_id:
